# Generated by Django 5.1.2 on 2025-04-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="can_add_room",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="can_delete_room",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="can_edit_room",
        ),
    ]
