# Generated by Django 5.1.2 on 2025-04-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_timeentry"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="timeentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("clock_out__isnull", True)),
                fields=("user",),
                name="uniq_open_entry_per_user",
            ),
        ),
    ]
