# Generated by Django 5.1.2 on 2025-04-13 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "permissions": [
                    ("can_edit_report", "Can edit report"),
                    ("can_delete_report", "Can delete report"),
                ]
            },
        ),
        migrations.AddField(
            model_name="report",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
