# Generated by Django 5.1.2 on 2025-04-08 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AddField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="id_card_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="id_card_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("passport", "Passport"),
                    ("national_id", "National ID"),
                    ("driver_license", "Driver’s Licence"),
                    ("voter_id", "Voter ID"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
