# Generated by Django 5.1.2 on 2025-04-28 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaint_tickets",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint Ticket",
                "verbose_name_plural": "Complaint Tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Laundry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_description", models.CharField(max_length=200)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_items",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Clothes"
                    ),
                ),
                (
                    "used_items",
                    models.PositiveIntegerField(default=0, verbose_name="Used Clothes"),
                ),
                (
                    "returned_items",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Returned/Unused Clothes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laundry_services",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Laundry Service",
                "verbose_name_plural": "Laundry Services",
                "ordering": ["-id"],
            },
        ),
    ]
